use_frameworks!

source 'http://git.bogokj.com/fandong/BogoSpec.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'FDUIKitObjC_Example' do
  pod 'FDUIKitObjC', :path => '../'

  target 'FDUIKitObjC_Tests' do
    inherit! :search_paths

    
  end
end
